// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package rpc is a generated GoMock package.
package rpc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s21platform/community-service/internal/model"
	community "github.com/s21platform/community-service/pkg/community"
)

// MockDbRepo is a mock of DbRepo interface.
type MockDbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepoMockRecorder
}

// MockDbRepoMockRecorder is the mock recorder for MockDbRepo.
type MockDbRepoMockRecorder struct {
	mock *MockDbRepo
}

// NewMockDbRepo creates a new mock instance.
func NewMockDbRepo(ctrl *gomock.Controller) *MockDbRepo {
	mock := &MockDbRepo{ctrl: ctrl}
	mock.recorder = &MockDbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbRepo) EXPECT() *MockDbRepoMockRecorder {
	return m.recorder
}

// GetPeerSchoolData mocks base method.
func (m *MockDbRepo) GetPeerSchoolData(ctx context.Context, nickName string) (model.PeerSchoolData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerSchoolData", ctx, nickName)
	ret0, _ := ret[0].(model.PeerSchoolData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerSchoolData indicates an expected call of GetPeerSchoolData.
func (mr *MockDbRepoMockRecorder) GetPeerSchoolData(ctx, nickName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerSchoolData", reflect.TypeOf((*MockDbRepo)(nil).GetPeerSchoolData), ctx, nickName)
}

// GetPeerStatus mocks base method.
func (m *MockDbRepo) GetPeerStatus(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerStatus", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerStatus indicates an expected call of GetPeerStatus.
func (mr *MockDbRepoMockRecorder) GetPeerStatus(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerStatus", reflect.TypeOf((*MockDbRepo)(nil).GetPeerStatus), ctx, email)
}

// GetStaffId mocks base method.
func (m *MockDbRepo) GetStaffId(ctx context.Context, login string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStaffId", ctx, login)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStaffId indicates an expected call of GetStaffId.
func (mr *MockDbRepoMockRecorder) GetStaffId(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStaffId", reflect.TypeOf((*MockDbRepo)(nil).GetStaffId), ctx, login)
}

// SearchPeersBySubstring mocks base method.
func (m *MockDbRepo) SearchPeersBySubstring(ctx context.Context, substring string) ([]*community.SearchPeer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPeersBySubstring", ctx, substring)
	ret0, _ := ret[0].([]*community.SearchPeer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPeersBySubstring indicates an expected call of SearchPeersBySubstring.
func (mr *MockDbRepoMockRecorder) SearchPeersBySubstring(ctx, substring interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPeersBySubstring", reflect.TypeOf((*MockDbRepo)(nil).SearchPeersBySubstring), ctx, substring)
}
