// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.28.1
// source: api/community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSchoolDataIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolDataIn) Reset() {
	*x = GetSchoolDataIn{}
	mi := &file_api_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolDataIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolDataIn) ProtoMessage() {}

func (x *GetSchoolDataIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolDataIn.ProtoReflect.Descriptor instead.
func (*GetSchoolDataIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{0}
}

func (x *GetSchoolDataIn) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type GetSchoolDataOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	ParallelName  string                 `protobuf:"bytes,2,opt,name=parallelName,proto3" json:"parallelName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolDataOut) Reset() {
	*x = GetSchoolDataOut{}
	mi := &file_api_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolDataOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolDataOut) ProtoMessage() {}

func (x *GetSchoolDataOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolDataOut.ProtoReflect.Descriptor instead.
func (*GetSchoolDataOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchoolDataOut) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *GetSchoolDataOut) GetParallelName() string {
	if x != nil {
		return x.ParallelName
	}
	return ""
}

type SearchPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPeer) Reset() {
	*x = SearchPeer{}
	mi := &file_api_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeer) ProtoMessage() {}

func (x *SearchPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeer.ProtoReflect.Descriptor instead.
func (*SearchPeer) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{2}
}

func (x *SearchPeer) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type ParticipantChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Login string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Types that are valid to be assigned to OldValue:
	//
	//	*ParticipantChangeEvent_OldValueStr
	//	*ParticipantChangeEvent_OldValueInt
	OldValue isParticipantChangeEvent_OldValue `protobuf_oneof:"old_value"`
	// Types that are valid to be assigned to NewValue:
	//
	//	*ParticipantChangeEvent_NewValueStr
	//	*ParticipantChangeEvent_NewValueInt
	NewValue      isParticipantChangeEvent_NewValue `protobuf_oneof:"new_value"`
	At            *timestamppb.Timestamp            `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantChangeEvent) Reset() {
	*x = ParticipantChangeEvent{}
	mi := &file_api_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantChangeEvent) ProtoMessage() {}

func (x *ParticipantChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantChangeEvent.ProtoReflect.Descriptor instead.
func (*ParticipantChangeEvent) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{3}
}

func (x *ParticipantChangeEvent) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ParticipantChangeEvent) GetOldValue() isParticipantChangeEvent_OldValue {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *ParticipantChangeEvent) GetOldValueStr() string {
	if x != nil {
		if x, ok := x.OldValue.(*ParticipantChangeEvent_OldValueStr); ok {
			return x.OldValueStr
		}
	}
	return ""
}

func (x *ParticipantChangeEvent) GetOldValueInt() int32 {
	if x != nil {
		if x, ok := x.OldValue.(*ParticipantChangeEvent_OldValueInt); ok {
			return x.OldValueInt
		}
	}
	return 0
}

func (x *ParticipantChangeEvent) GetNewValue() isParticipantChangeEvent_NewValue {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *ParticipantChangeEvent) GetNewValueStr() string {
	if x != nil {
		if x, ok := x.NewValue.(*ParticipantChangeEvent_NewValueStr); ok {
			return x.NewValueStr
		}
	}
	return ""
}

func (x *ParticipantChangeEvent) GetNewValueInt() int32 {
	if x != nil {
		if x, ok := x.NewValue.(*ParticipantChangeEvent_NewValueInt); ok {
			return x.NewValueInt
		}
	}
	return 0
}

func (x *ParticipantChangeEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type isParticipantChangeEvent_OldValue interface {
	isParticipantChangeEvent_OldValue()
}

type ParticipantChangeEvent_OldValueStr struct {
	OldValueStr string `protobuf:"bytes,2,opt,name=old_value_str,json=oldValueStr,proto3,oneof"`
}

type ParticipantChangeEvent_OldValueInt struct {
	OldValueInt int32 `protobuf:"varint,3,opt,name=old_value_int,json=oldValueInt,proto3,oneof"`
}

func (*ParticipantChangeEvent_OldValueStr) isParticipantChangeEvent_OldValue() {}

func (*ParticipantChangeEvent_OldValueInt) isParticipantChangeEvent_OldValue() {}

type isParticipantChangeEvent_NewValue interface {
	isParticipantChangeEvent_NewValue()
}

type ParticipantChangeEvent_NewValueStr struct {
	NewValueStr string `protobuf:"bytes,4,opt,name=new_value_str,json=newValueStr,proto3,oneof"`
}

type ParticipantChangeEvent_NewValueInt struct {
	NewValueInt int32 `protobuf:"varint,5,opt,name=new_value_int,json=newValueInt,proto3,oneof"`
}

func (*ParticipantChangeEvent_NewValueStr) isParticipantChangeEvent_NewValue() {}

func (*ParticipantChangeEvent_NewValueInt) isParticipantChangeEvent_NewValue() {}

type GetStudentDataIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid пользователя, которого запрашивают
	UserUUID      string `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentDataIn) Reset() {
	*x = GetStudentDataIn{}
	mi := &file_api_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentDataIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentDataIn) ProtoMessage() {}

func (x *GetStudentDataIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentDataIn.ProtoReflect.Descriptor instead.
func (*GetStudentDataIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentDataIn) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

// Навыки студента
type Skill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название навыка
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Кол-во очков, по данному навыку
	Points        int32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_api_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{5}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

// Достижения студента
type Badge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Наименование достижеиня
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Ссылка на иконку
	IconUrl string `protobuf:"bytes,2,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// Дата получения
	ReceiptDateTime string `protobuf:"bytes,3,opt,name=receipt_date_time,json=receiptDateTime,proto3" json:"receipt_date_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Badge) Reset() {
	*x = Badge{}
	mi := &file_api_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Badge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Badge) ProtoMessage() {}

func (x *Badge) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Badge.ProtoReflect.Descriptor instead.
func (*Badge) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{6}
}

func (x *Badge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Badge) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *Badge) GetReceiptDateTime() string {
	if x != nil {
		return x.ReceiptDateTime
	}
	return ""
}

type GetStudentDataOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин студента
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Id кампуса
	CampusId int64 `protobuf:"varint,2,opt,name=campusId,proto3" json:"campusId,omitempty"`
	// Название класса/группы
	ClassName string `protobuf:"bytes,3,opt,name=className,proto3" json:"className,omitempty"`
	// Наименование волны
	ParallelName string `protobuf:"bytes,4,opt,name=parallelName,proto3" json:"parallelName,omitempty"`
	// Id трайба
	TribeId int64 `protobuf:"varint,5,opt,name=tribeId,proto3" json:"tribeId,omitempty"`
	// Статус
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Время зачисления
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Кол-во опыта
	ExpValue int64 `protobuf:"varint,8,opt,name=exp_value,json=expValue,proto3" json:"exp_value,omitempty"`
	// Уровень
	Level int64 `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	// Кол-во опыта до следующего лвл
	ExpToNextLevel int64 `protobuf:"varint,10,opt,name=exp_to_next_level,json=expToNextLevel,proto3" json:"exp_to_next_level,omitempty"`
	// Кол-во поинтов для проверок
	Crp int64 `protobuf:"varint,11,opt,name=crp,proto3" json:"crp,omitempty"`
	// Навыки студента
	Skills []*Skill `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	// Кол-во поинтов для ревью
	Prp int64 `protobuf:"varint,13,opt,name=prp,proto3" json:"prp,omitempty"`
	// Кол-во валюты
	Coins int64 `protobuf:"varint,14,opt,name=coins,proto3" json:"coins,omitempty"`
	// Достижения студента
	Badges        []*Badge `protobuf:"bytes,15,rep,name=badges,proto3" json:"badges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentDataOut) Reset() {
	*x = GetStudentDataOut{}
	mi := &file_api_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentDataOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentDataOut) ProtoMessage() {}

func (x *GetStudentDataOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentDataOut.ProtoReflect.Descriptor instead.
func (*GetStudentDataOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{7}
}

func (x *GetStudentDataOut) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetStudentDataOut) GetCampusId() int64 {
	if x != nil {
		return x.CampusId
	}
	return 0
}

func (x *GetStudentDataOut) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *GetStudentDataOut) GetParallelName() string {
	if x != nil {
		return x.ParallelName
	}
	return ""
}

func (x *GetStudentDataOut) GetTribeId() int64 {
	if x != nil {
		return x.TribeId
	}
	return 0
}

func (x *GetStudentDataOut) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStudentDataOut) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetStudentDataOut) GetExpValue() int64 {
	if x != nil {
		return x.ExpValue
	}
	return 0
}

func (x *GetStudentDataOut) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetStudentDataOut) GetExpToNextLevel() int64 {
	if x != nil {
		return x.ExpToNextLevel
	}
	return 0
}

func (x *GetStudentDataOut) GetCrp() int64 {
	if x != nil {
		return x.Crp
	}
	return 0
}

func (x *GetStudentDataOut) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetStudentDataOut) GetPrp() int64 {
	if x != nil {
		return x.Prp
	}
	return 0
}

func (x *GetStudentDataOut) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *GetStudentDataOut) GetBadges() []*Badge {
	if x != nil {
		return x.Badges
	}
	return nil
}

type ValidateCodeIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Код
	Code          int64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCodeIn) Reset() {
	*x = ValidateCodeIn{}
	mi := &file_api_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCodeIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCodeIn) ProtoMessage() {}

func (x *ValidateCodeIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCodeIn.ProtoReflect.Descriptor instead.
func (*ValidateCodeIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateCodeIn) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ValidateCodeIn) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ValidateCodeOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сообщение
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCodeOut) Reset() {
	*x = ValidateCodeOut{}
	mi := &file_api_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCodeOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCodeOut) ProtoMessage() {}

func (x *ValidateCodeOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCodeOut.ProtoReflect.Descriptor instead.
func (*ValidateCodeOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateCodeOut) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_community_proto protoreflect.FileDescriptor

const file_api_community_proto_rawDesc = "" +
	"\n" +
	"\x13api/community.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x0fGetSchoolDataIn\x12\x1a\n" +
	"\bnickName\x18\x01 \x01(\tR\bnickName\"T\n" +
	"\x10GetSchoolDataOut\x12\x1c\n" +
	"\tclassName\x18\x01 \x01(\tR\tclassName\x12\"\n" +
	"\fparallelName\x18\x02 \x01(\tR\fparallelName\"\"\n" +
	"\n" +
	"SearchPeer\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"\x8c\x02\n" +
	"\x16ParticipantChangeEvent\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12$\n" +
	"\rold_value_str\x18\x02 \x01(\tH\x00R\voldValueStr\x12$\n" +
	"\rold_value_int\x18\x03 \x01(\x05H\x00R\voldValueInt\x12$\n" +
	"\rnew_value_str\x18\x04 \x01(\tH\x01R\vnewValueStr\x12$\n" +
	"\rnew_value_int\x18\x05 \x01(\x05H\x01R\vnewValueInt\x12*\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02atB\v\n" +
	"\told_valueB\v\n" +
	"\tnew_value\".\n" +
	"\x10GetStudentDataIn\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\"3\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\"b\n" +
	"\x05Badge\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x02 \x01(\tR\aiconUrl\x12*\n" +
	"\x11receipt_date_time\x18\x03 \x01(\tR\x0freceiptDateTime\"\xb0\x03\n" +
	"\x11GetStudentDataOut\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bcampusId\x18\x02 \x01(\x03R\bcampusId\x12\x1c\n" +
	"\tclassName\x18\x03 \x01(\tR\tclassName\x12\"\n" +
	"\fparallelName\x18\x04 \x01(\tR\fparallelName\x12\x18\n" +
	"\atribeId\x18\x05 \x01(\x03R\atribeId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\texp_value\x18\b \x01(\x03R\bexpValue\x12\x14\n" +
	"\x05level\x18\t \x01(\x03R\x05level\x12)\n" +
	"\x11exp_to_next_level\x18\n" +
	" \x01(\x03R\x0eexpToNextLevel\x12\x10\n" +
	"\x03crp\x18\v \x01(\x03R\x03crp\x12\x1e\n" +
	"\x06skills\x18\f \x03(\v2\x06.SkillR\x06skills\x12\x10\n" +
	"\x03prp\x18\r \x01(\x03R\x03prp\x12\x14\n" +
	"\x05coins\x18\x0e \x01(\x03R\x05coins\x12\x1e\n" +
	"\x06badges\x18\x0f \x03(\v2\x06.BadgeR\x06badges\":\n" +
	"\x0eValidateCodeIn\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"+\n" +
	"\x0fValidateCodeOut\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbe\x01\n" +
	"\x10CommunityService\x12:\n" +
	"\x11GetPeerSchoolData\x12\x10.GetSchoolDataIn\x1a\x11.GetSchoolDataOut\"\x00\x129\n" +
	"\x0eGetStudentData\x12\x11.GetStudentDataIn\x1a\x12.GetStudentDataOut\"\x00\x123\n" +
	"\fValidateCode\x12\x0f.ValidateCodeIn\x1a\x10.ValidateCodeOut\"\x00B\x0fZ\rpkg/communityb\x06proto3"

var (
	file_api_community_proto_rawDescOnce sync.Once
	file_api_community_proto_rawDescData []byte
)

func file_api_community_proto_rawDescGZIP() []byte {
	file_api_community_proto_rawDescOnce.Do(func() {
		file_api_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_community_proto_rawDesc), len(file_api_community_proto_rawDesc)))
	})
	return file_api_community_proto_rawDescData
}

var file_api_community_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_community_proto_goTypes = []any{
	(*GetSchoolDataIn)(nil),        // 0: GetSchoolDataIn
	(*GetSchoolDataOut)(nil),       // 1: GetSchoolDataOut
	(*SearchPeer)(nil),             // 2: SearchPeer
	(*ParticipantChangeEvent)(nil), // 3: ParticipantChangeEvent
	(*GetStudentDataIn)(nil),       // 4: GetStudentDataIn
	(*Skill)(nil),                  // 5: Skill
	(*Badge)(nil),                  // 6: Badge
	(*GetStudentDataOut)(nil),      // 7: GetStudentDataOut
	(*ValidateCodeIn)(nil),         // 8: ValidateCodeIn
	(*ValidateCodeOut)(nil),        // 9: ValidateCodeOut
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
}
var file_api_community_proto_depIdxs = []int32{
	10, // 0: ParticipantChangeEvent.at:type_name -> google.protobuf.Timestamp
	5,  // 1: GetStudentDataOut.skills:type_name -> Skill
	6,  // 2: GetStudentDataOut.badges:type_name -> Badge
	0,  // 3: CommunityService.GetPeerSchoolData:input_type -> GetSchoolDataIn
	4,  // 4: CommunityService.GetStudentData:input_type -> GetStudentDataIn
	8,  // 5: CommunityService.ValidateCode:input_type -> ValidateCodeIn
	1,  // 6: CommunityService.GetPeerSchoolData:output_type -> GetSchoolDataOut
	7,  // 7: CommunityService.GetStudentData:output_type -> GetStudentDataOut
	9,  // 8: CommunityService.ValidateCode:output_type -> ValidateCodeOut
	6,  // [6:9] is the sub-list for method output_type
	3,  // [3:6] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_community_proto_init() }
func file_api_community_proto_init() {
	if File_api_community_proto != nil {
		return
	}
	file_api_community_proto_msgTypes[3].OneofWrappers = []any{
		(*ParticipantChangeEvent_OldValueStr)(nil),
		(*ParticipantChangeEvent_OldValueInt)(nil),
		(*ParticipantChangeEvent_NewValueStr)(nil),
		(*ParticipantChangeEvent_NewValueInt)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_community_proto_rawDesc), len(file_api_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_community_proto_goTypes,
		DependencyIndexes: file_api_community_proto_depIdxs,
		MessageInfos:      file_api_community_proto_msgTypes,
	}.Build()
	File_api_community_proto = out.File
	file_api_community_proto_goTypes = nil
	file_api_community_proto_depIdxs = nil
}
