// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: api/community.proto

package community

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommunityService_GetPeerSchoolData_FullMethodName = "/CommunityService/GetPeerSchoolData"
	CommunityService_GetStudentData_FullMethodName    = "/CommunityService/GetStudentData"
	CommunityService_ValidateCode_FullMethodName      = "/CommunityService/ValidateCode"
)

// CommunityServiceClient is the client API for CommunityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service with peers' info from edu platform
type CommunityServiceClient interface {
	GetPeerSchoolData(ctx context.Context, in *GetSchoolDataIn, opts ...grpc.CallOption) (*GetSchoolDataOut, error)
	// Ручка получения данных школьников
	GetStudentData(ctx context.Context, in *GetStudentDataIn, opts ...grpc.CallOption) (*GetStudentDataOut, error)
	// Ручка подтверждения кода
	ValidateCode(ctx context.Context, in *ValidateCodeIn, opts ...grpc.CallOption) (*ValidateCodeOut, error)
}

type communityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunityServiceClient(cc grpc.ClientConnInterface) CommunityServiceClient {
	return &communityServiceClient{cc}
}

func (c *communityServiceClient) GetPeerSchoolData(ctx context.Context, in *GetSchoolDataIn, opts ...grpc.CallOption) (*GetSchoolDataOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchoolDataOut)
	err := c.cc.Invoke(ctx, CommunityService_GetPeerSchoolData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) GetStudentData(ctx context.Context, in *GetStudentDataIn, opts ...grpc.CallOption) (*GetStudentDataOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentDataOut)
	err := c.cc.Invoke(ctx, CommunityService_GetStudentData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *communityServiceClient) ValidateCode(ctx context.Context, in *ValidateCodeIn, opts ...grpc.CallOption) (*ValidateCodeOut, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCodeOut)
	err := c.cc.Invoke(ctx, CommunityService_ValidateCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommunityServiceServer is the server API for CommunityService service.
// All implementations must embed UnimplementedCommunityServiceServer
// for forward compatibility.
//
// Service with peers' info from edu platform
type CommunityServiceServer interface {
	GetPeerSchoolData(context.Context, *GetSchoolDataIn) (*GetSchoolDataOut, error)
	// Ручка получения данных школьников
	GetStudentData(context.Context, *GetStudentDataIn) (*GetStudentDataOut, error)
	// Ручка подтверждения кода
	ValidateCode(context.Context, *ValidateCodeIn) (*ValidateCodeOut, error)
	mustEmbedUnimplementedCommunityServiceServer()
}

// UnimplementedCommunityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommunityServiceServer struct{}

func (UnimplementedCommunityServiceServer) GetPeerSchoolData(context.Context, *GetSchoolDataIn) (*GetSchoolDataOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerSchoolData not implemented")
}
func (UnimplementedCommunityServiceServer) GetStudentData(context.Context, *GetStudentDataIn) (*GetStudentDataOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentData not implemented")
}
func (UnimplementedCommunityServiceServer) ValidateCode(context.Context, *ValidateCodeIn) (*ValidateCodeOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCode not implemented")
}
func (UnimplementedCommunityServiceServer) mustEmbedUnimplementedCommunityServiceServer() {}
func (UnimplementedCommunityServiceServer) testEmbeddedByValue()                          {}

// UnsafeCommunityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunityServiceServer will
// result in compilation errors.
type UnsafeCommunityServiceServer interface {
	mustEmbedUnimplementedCommunityServiceServer()
}

func RegisterCommunityServiceServer(s grpc.ServiceRegistrar, srv CommunityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommunityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommunityService_ServiceDesc, srv)
}

func _CommunityService_GetPeerSchoolData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchoolDataIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetPeerSchoolData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetPeerSchoolData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetPeerSchoolData(ctx, req.(*GetSchoolDataIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_GetStudentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentDataIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).GetStudentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_GetStudentData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).GetStudentData(ctx, req.(*GetStudentDataIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommunityService_ValidateCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCodeIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommunityServiceServer).ValidateCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommunityService_ValidateCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommunityServiceServer).ValidateCode(ctx, req.(*ValidateCodeIn))
	}
	return interceptor(ctx, in, info, handler)
}

// CommunityService_ServiceDesc is the grpc.ServiceDesc for CommunityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommunityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CommunityService",
	HandlerType: (*CommunityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeerSchoolData",
			Handler:    _CommunityService_GetPeerSchoolData_Handler,
		},
		{
			MethodName: "GetStudentData",
			Handler:    _CommunityService_GetStudentData_Handler,
		},
		{
			MethodName: "ValidateCode",
			Handler:    _CommunityService_ValidateCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/community.proto",
}
