// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.1
// source: api/community.proto

package community

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsUserStaffOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsStaff bool `protobuf:"varint,1,opt,name=isStaff,proto3" json:"isStaff,omitempty"`
}

func (x *IsUserStaffOut) Reset() {
	*x = IsUserStaffOut{}
	mi := &file_api_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserStaffOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserStaffOut) ProtoMessage() {}

func (x *IsUserStaffOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserStaffOut.ProtoReflect.Descriptor instead.
func (*IsUserStaffOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{0}
}

func (x *IsUserStaffOut) GetIsStaff() bool {
	if x != nil {
		return x.IsStaff
	}
	return false
}

type LoginIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *LoginIn) Reset() {
	*x = LoginIn{}
	mi := &file_api_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIn) ProtoMessage() {}

func (x *LoginIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIn.ProtoReflect.Descriptor instead.
func (*LoginIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{1}
}

func (x *LoginIn) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetSchoolDataIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
}

func (x *GetSchoolDataIn) Reset() {
	*x = GetSchoolDataIn{}
	mi := &file_api_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolDataIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolDataIn) ProtoMessage() {}

func (x *GetSchoolDataIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolDataIn.ProtoReflect.Descriptor instead.
func (*GetSchoolDataIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchoolDataIn) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type GetSchoolDataOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName    string `protobuf:"bytes,1,opt,name=className,proto3" json:"className,omitempty"`
	ParallelName string `protobuf:"bytes,2,opt,name=parallelName,proto3" json:"parallelName,omitempty"`
}

func (x *GetSchoolDataOut) Reset() {
	*x = GetSchoolDataOut{}
	mi := &file_api_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolDataOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolDataOut) ProtoMessage() {}

func (x *GetSchoolDataOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolDataOut.ProtoReflect.Descriptor instead.
func (*GetSchoolDataOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{3}
}

func (x *GetSchoolDataOut) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *GetSchoolDataOut) GetParallelName() string {
	if x != nil {
		return x.ParallelName
	}
	return ""
}

// Data for searching for matches in peers' info
type EmailIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User's E-mail address
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailIn) Reset() {
	*x = EmailIn{}
	mi := &file_api_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailIn) ProtoMessage() {}

func (x *EmailIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailIn.ProtoReflect.Descriptor instead.
func (*EmailIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{4}
}

func (x *EmailIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Response with found match
type EmailOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
}

func (x *EmailOut) Reset() {
	*x = EmailOut{}
	mi := &file_api_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailOut) ProtoMessage() {}

func (x *EmailOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailOut.ProtoReflect.Descriptor instead.
func (*EmailOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{5}
}

func (x *EmailOut) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type SearchPeersIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Substring string `protobuf:"bytes,1,opt,name=substring,proto3" json:"substring,omitempty"`
	Limit     int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset    int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *SearchPeersIn) Reset() {
	*x = SearchPeersIn{}
	mi := &file_api_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeersIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeersIn) ProtoMessage() {}

func (x *SearchPeersIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeersIn.ProtoReflect.Descriptor instead.
func (*SearchPeersIn) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{6}
}

func (x *SearchPeersIn) GetSubstring() string {
	if x != nil {
		return x.Substring
	}
	return ""
}

func (x *SearchPeersIn) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchPeersIn) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *SearchPeer) Reset() {
	*x = SearchPeer{}
	mi := &file_api_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeer) ProtoMessage() {}

func (x *SearchPeer) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeer.ProtoReflect.Descriptor instead.
func (*SearchPeer) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{7}
}

func (x *SearchPeer) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type SearchPeersOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchPeers []*SearchPeer `protobuf:"bytes,1,rep,name=searchPeers,proto3" json:"searchPeers,omitempty"`
}

func (x *SearchPeersOut) Reset() {
	*x = SearchPeersOut{}
	mi := &file_api_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPeersOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPeersOut) ProtoMessage() {}

func (x *SearchPeersOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPeersOut.ProtoReflect.Descriptor instead.
func (*SearchPeersOut) Descriptor() ([]byte, []int) {
	return file_api_community_proto_rawDescGZIP(), []int{8}
}

func (x *SearchPeersOut) GetSearchPeers() []*SearchPeer {
	if x != nil {
		return x.SearchPeers
	}
	return nil
}

var File_api_community_proto protoreflect.FileDescriptor

var file_api_community_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0e, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x22, 0x1f,
	0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22,
	0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x54,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4f,
	0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x24, 0x0a, 0x08, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4f, 0x75,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x50, 0x65, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x3f, 0x0a, 0x0e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x65, 0x72, 0x73, 0x4f, 0x75, 0x74, 0x12, 0x2d,
	0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x65, 0x72, 0x73, 0x32, 0x9d, 0x02,
	0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x49, 0x73, 0x50, 0x65, 0x65, 0x72, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x12, 0x08, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x1a, 0x09, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x4f, 0x75, 0x74, 0x12, 0x30, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x49, 0x6e, 0x1a, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x65, 0x72, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x1a,
	0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x4f,
	0x75, 0x74, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0b, 0x69, 0x73, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x12, 0x08, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x1a, 0x0f, 0x2e,
	0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x66, 0x66, 0x4f, 0x75, 0x74, 0x22, 0x00,
	0x12, 0x4b, 0x0a, 0x17, 0x52, 0x75, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x0f, 0x5a,
	0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_community_proto_rawDescOnce sync.Once
	file_api_community_proto_rawDescData = file_api_community_proto_rawDesc
)

func file_api_community_proto_rawDescGZIP() []byte {
	file_api_community_proto_rawDescOnce.Do(func() {
		file_api_community_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_community_proto_rawDescData)
	})
	return file_api_community_proto_rawDescData
}

var file_api_community_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_community_proto_goTypes = []any{
	(*IsUserStaffOut)(nil),   // 0: IsUserStaffOut
	(*LoginIn)(nil),          // 1: LoginIn
	(*GetSchoolDataIn)(nil),  // 2: GetSchoolDataIn
	(*GetSchoolDataOut)(nil), // 3: GetSchoolDataOut
	(*EmailIn)(nil),          // 4: EmailIn
	(*EmailOut)(nil),         // 5: EmailOut
	(*SearchPeersIn)(nil),    // 6: SearchPeersIn
	(*SearchPeer)(nil),       // 7: SearchPeer
	(*SearchPeersOut)(nil),   // 8: SearchPeersOut
	(*emptypb.Empty)(nil),    // 9: google.protobuf.Empty
}
var file_api_community_proto_depIdxs = []int32{
	7, // 0: SearchPeersOut.searchPeers:type_name -> SearchPeer
	4, // 1: CommunityService.IsPeerExist:input_type -> EmailIn
	6, // 2: CommunityService.SearchPeers:input_type -> SearchPeersIn
	2, // 3: CommunityService.GetPeerSchoolData:input_type -> GetSchoolDataIn
	1, // 4: CommunityService.isUserStaff:input_type -> LoginIn
	9, // 5: CommunityService.RunLoginsWorkerManually:input_type -> google.protobuf.Empty
	5, // 6: CommunityService.IsPeerExist:output_type -> EmailOut
	8, // 7: CommunityService.SearchPeers:output_type -> SearchPeersOut
	3, // 8: CommunityService.GetPeerSchoolData:output_type -> GetSchoolDataOut
	0, // 9: CommunityService.isUserStaff:output_type -> IsUserStaffOut
	9, // 10: CommunityService.RunLoginsWorkerManually:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_community_proto_init() }
func file_api_community_proto_init() {
	if File_api_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_community_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_community_proto_goTypes,
		DependencyIndexes: file_api_community_proto_depIdxs,
		MessageInfos:      file_api_community_proto_msgTypes,
	}.Build()
	File_api_community_proto = out.File
	file_api_community_proto_rawDesc = nil
	file_api_community_proto_goTypes = nil
	file_api_community_proto_depIdxs = nil
}
