openapi: 3.0.3
info:
  title: User Service
  version: 1.0.0

paths:
  /api/community/send_linking_code:
    post:
      summary: Ручка для отправки кода линковки к School 21
      operationId: SendLinkingCode
      parameters:
        - name: X-User-Uuid
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendLinkingCodeData'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        500:
          $ref: '#/components/responses/InternalError'


components:
  schemas:
    SendLinkingCodeData:
      type: object
      required:
        - login
      properties:
        login:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource is not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
